name: Release

on:
  push:
    branches:    
      - master 

jobs:

  build_core:
    name: Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: master
     
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set up Apache Maven
        uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.5.4
  
      - name: Publish
        run: ./build.sh
